package com.dldmswo1209.chatbot.todayTodo

import com.dldmswo1209.chatbot.todayTodo.TodoItem.Companion.STATE_RECOMMEND_WORK

val recommendList = mutableListOf<TodoItem>(
    TodoItem("동네를 한바퀴 산책하기","한바퀴 산책하면서 바람맞았어요",STATE_RECOMMEND_WORK),
    TodoItem("끝까지 숙제하기","보람차게 숙제를 다 했어요!",STATE_RECOMMEND_WORK),
    TodoItem("맛있는 간식먹기","오늘도 수고한 나에게 간식을 선물해요",STATE_RECOMMEND_WORK),
    TodoItem("나른하게 낮잠자기","낮잠을 자는 것은 피로회복에 큰 도움이 돼요",STATE_RECOMMEND_WORK),
    TodoItem("즐겁게 샤워하기","샤워를 하며 상쾌한 기분을 느꼈어요!",STATE_RECOMMEND_WORK),
    TodoItem("규칙적인 시간에 취침하고, 일어나기","",STATE_RECOMMEND_WORK),
    TodoItem("잠들기 전 2시간 전에 스마트폰 내려놓기","",STATE_RECOMMEND_WORK),
    TodoItem("편안하게 명상하기","",STATE_RECOMMEND_WORK),
    TodoItem("집중하여 독서하기","",STATE_RECOMMEND_WORK),
    TodoItem("친구들과 수다떨기","",STATE_RECOMMEND_WORK),
    TodoItem("좋아하는 노래 듣기","",STATE_RECOMMEND_WORK),
    TodoItem("땀흘리며 열심히 운동하기","",STATE_RECOMMEND_WORK),
    TodoItem("카페가기","",STATE_RECOMMEND_WORK),
    TodoItem("산책하기","",STATE_RECOMMEND_WORK),
    TodoItem("영화보기","",STATE_RECOMMEND_WORK),
    TodoItem("드라마보기","",STATE_RECOMMEND_WORK),
    TodoItem("책 읽기","",STATE_RECOMMEND_WORK),
    TodoItem("공부하기","",STATE_RECOMMEND_WORK),
    TodoItem("요리하기","",STATE_RECOMMEND_WORK),
    TodoItem("산책하기","",STATE_RECOMMEND_WORK),
    TodoItem("낮잠자기","",STATE_RECOMMEND_WORK),
    TodoItem("음악듣기","",STATE_RECOMMEND_WORK),
    TodoItem("게임하기","",STATE_RECOMMEND_WORK),
    TodoItem("여행가기","",STATE_RECOMMEND_WORK),
    TodoItem("그림 그리기","",STATE_RECOMMEND_WORK),
    TodoItem("예능보기","",STATE_RECOMMEND_WORK),
    TodoItem("외식하기","",STATE_RECOMMEND_WORK),
    TodoItem("쇼핑하기","",STATE_RECOMMEND_WORK),
    TodoItem("사진찍기","",STATE_RECOMMEND_WORK),
)