package com.dldmswo1209.chatbot.todayTodo

val recommendList = mutableListOf<TodoItem>(
    TodoItem("숙제하기",""),
    TodoItem("일기쓰기",""),
    TodoItem("운동하기",""),
    TodoItem("코딩하기",""),
    TodoItem("샤워하기",""),
    TodoItem("카페가기",""),
    TodoItem("산책하기",""),
    TodoItem("영화보기",""),
    TodoItem("드라마보기",""),
    TodoItem("책 읽기",""),
    TodoItem("공부하기",""),
    TodoItem("요리하기",""),
    TodoItem("산책하기",""),
    TodoItem("낮잠자기",""),
    TodoItem("음악듣기",""),
    TodoItem("게임하기",""),
    TodoItem("여행가기",""),
    TodoItem("그림 그리기",""),
    TodoItem("예능보기",""),
    TodoItem("외식하기",""),
    TodoItem("쇼핑하기",""),
    TodoItem("사진찍기",""),
)